from pathlib import Path

from frameq_worker.subtitles import find_subtitle_transcript


def test_find_subtitle_transcript_prefers_configured_languages_and_parses_srt(
    tmp_path: Path,
) -> None:
    (tmp_path / "demo.en.srt").write_text(
        "1\n00:00:00,000 --> 00:00:01,000\nEnglish line\n",
        encoding="utf-8",
    )
    (tmp_path / "demo.zh-Hans.srt").write_text(
        "1\n00:00:01,200 --> 00:00:02,400\n第一句\n\n"
        "2\n00:00:02,500 --> 00:00:03,000\n第二句\n",
        encoding="utf-8",
    )
    (tmp_path / "demo.zh.srt").write_text(
        "1\n00:00:00,000 --> 00:00:01,000\n通用中文\n",
        encoding="utf-8",
    )

    transcript = find_subtitle_transcript(tmp_path)

    assert transcript is not None
    assert transcript.language == "zh-Hans"
    assert transcript.text == "第一句\n第二句"
    assert [segment.to_json() for segment in transcript.segments] == [
        {"id": "subtitle-1", "start_ms": 1200, "end_ms": 2400, "text": "第一句"},
        {"id": "subtitle-2", "start_ms": 2500, "end_ms": 3000, "text": "第二句"},
    ]


def test_find_subtitle_transcript_prefers_generic_chinese_over_english(
    tmp_path: Path,
) -> None:
    (tmp_path / "demo.en.vtt").write_text(
        "WEBVTT\n\n00:00:00.000 --> 00:00:01.000\nEnglish line\n",
        encoding="utf-8",
    )
    (tmp_path / "demo.zh.vtt").write_text(
        "WEBVTT\n\n00:00:00.000 --> 00:00:01.000\n通用中文字幕\n",
        encoding="utf-8",
    )

    transcript = find_subtitle_transcript(tmp_path)

    assert transcript is not None
    assert transcript.language == "zh"
    assert transcript.text == "通用中文字幕"


def test_find_subtitle_transcript_cleans_vtt_controls_tags_and_rolling_duplicates(
    tmp_path: Path,
) -> None:
    (tmp_path / "video.en.vtt").write_text(
        "WEBVTT\n\n"
        "NOTE generated by platform\n"
        "ignore this\n\n"
        "STYLE\n"
        "::cue { color: white }\n\n"
        "cue-1\n"
        "00:00:00.000 --> 00:00:01.000 align:start position:0%\n"
        "<c>Hello</c>\n\n"
        "00:00:01.000 --> 00:00:02.000\n"
        "<c>Hello world</c> &amp; friends\n\n"
        "00:00:03.000 --> 00:00:04.000\n"
        "<i>Next</i> line <00:00:03.500>\n",
        encoding="utf-8",
    )

    transcript = find_subtitle_transcript(tmp_path)

    assert transcript is not None
    assert transcript.language == "en"
    assert transcript.text == "Hello world & friends\nNext line"
    assert [segment.text for segment in transcript.segments] == [
        "Hello world & friends",
        "Next line",
    ]


def test_find_subtitle_transcript_returns_none_for_invalid_or_empty_files(
    tmp_path: Path,
) -> None:
    (tmp_path / "broken.zh-CN.srt").write_text(
        "1\nnot a timestamp\n\n2\n00:00:01,000 --> 00:00:02,000\n   \n",
        encoding="utf-8",
    )

    assert find_subtitle_transcript(tmp_path) is None
