from __future__ import annotations

from collections.abc import Callable

PROGRESS_EVENT_PREFIX = "FRAMEQ_PROGRESS "
MODEL_DOWNLOAD_EVENT_PREFIX = "FRAMEQ_MODEL_DOWNLOAD "
PROCESS_VIDEO_CONTRACT_VERSION = 3

OUTPUT_DIR_ENV = "FRAMEQ_OUTPUT_DIR"
CACHE_DIR_ENV = "FRAMEQ_CACHE_DIR"
ASR_MODEL_ENV = "FRAMEQ_ASR_MODEL"
MODEL_DIR_ENV = "FRAMEQ_MODEL_DIR"
MODEL_DOWNLOAD_URL_ENV = "FRAMEQ_ASR_MODEL_DOWNLOAD_URL"
MODEL_DOWNLOAD_SHA256_ENV = "FRAMEQ_ASR_MODEL_DOWNLOAD_SHA256"
MODELSCOPE_ENDPOINT_ENV = "FRAMEQ_MODELSCOPE_ENDPOINT"
SENSEVOICE_REVISION_ENV = "FRAMEQ_SENSEVOICE_REVISION"

ProgressCallback = Callable[[dict[str, object]], None]
